#!/bin/bash

err_file_path="./err_logs/err_log_for_database_setup.txt"

if [ -f $err_file_path ]
then
	rm $err_file_path
	touch $err_file_path
else
	touch $err_file_path
fi

exec 2>$err_file_path

while [ -n "$1" ]
do
  case "$1" in
    -f)
      query_path="$2"
      shift;;
    *)
      echo "$1 is not option!" >&2
      exit 1
      break;;
	esac
		shift
done

while read sql_query
do
  mysql -h127.0.0.1 -P3306 -uroot -ppass -e "$sql_query"
done < $query_path
